var data = Object.keys(window);
var def = ["speechSynthesis","caches","localStorage","sessionStorage","webkitStorageInfo","indexedDB","webkitIndexedDB","ondeviceorientationabsolute","ondeviceorientation","ondevicemotion","crypto","postMessage","blur","focus","close","stop","open","alert","applicationCache","confirm","prompt","print","requestAnimationFrame","cancelAnimationFrame","captureEvents","releaseEvents","getComputedStyle","matchMedia","moveTo","moveBy","resizeTo","resizeBy","getSelection","find","getMatchedCSSRules","webkitRequestAnimationFrame","webkitCancelAnimationFrame","webkitCancelRequestAnimationFrame","btoa","atob","setTimeout","clearTimeout","setInterval","clearInterval","createImageBitmap","requestIdleCallback","cancelIdleCallback","scroll","scrollTo","scrollBy","fetch","webkitRequestFileSystem","webkitResolveLocalFileSystemURL","openDatabase","external","chrome","console","performance","onunload","onunhandledrejection","onstorage","onrejectionhandled","onpopstate","onpageshow","onpagehide","ononline","onoffline","onmessage","onlanguagechange","onhashchange","onbeforeunload","onwaiting","onvolumechange","ontoggle","ontimeupdate","onsuspend","onsubmit","onstalled","onshow","onselect","onseeking","onseeked","onscroll","onresize","onreset","onratechange","onprogress","onplaying","onplay","onpause","onmousewheel","onmouseup","onmouseover","onmouseout","onmousemove","onmouseleave","onmouseenter","onmousedown","onloadstart","onloadedmetadata","onloadeddata","onload","onkeyup","onkeypress","onkeydown","oninvalid","oninput","onfocus","onerror","onended","onemptied","ondurationchange","ondrop","ondragstart","ondragover","ondragleave","ondragenter","ondragend","ondrag","ondblclick","oncuechange","oncontextmenu","onclose","onclick","onchange","oncanplaythrough","oncanplay","oncancel","onblur","onabort","isSecureContext","onwheel","onwebkittransitionend","onwebkitanimationstart","onwebkitanimationiteration","onwebkitanimationend","ontransitionend","onsearch","onanimationstart","onanimationiteration","onanimationend","styleMedia","defaultstatus","defaultStatus","screenTop","screenLeft","clientInformation","devicePixelRatio","outerHeight","outerWidth","screenY","screenX","pageYOffset","scrollY","pageXOffset","scrollX","innerHeight","innerWidth","screen","navigator","frameElement","parent","opener","top","length","frames","closed","status","toolbar","statusbar","scrollbars","personalbar","menubar","locationbar","history","location","name","document","self","window","data","def","comp1","output","i","output"];
var comp1 = [];
var output = [];
for(var i = 0;i<def.length;i++){
  comp1[def[i]]=true;
}
for(var i = 0;i<data.length;i++){
  if(comp1[data[i]]!== true)output.push(data[i]);
}
alert(output.toString().replace(/,/gm,"\n"));
